### ISSUE TITLE
NotImplementedError: MyWidget is missing a QuerySet. Define MyWidget.model, MyWidget.queryset, or override MyWidget.get_queryset().

### ISSUE THREAD

**Issue by belongwqz** [applegrew/django-select2#341]
django's official note is as fllow:

"
django.Template.render() prohibits non-dict context¶
For compatibility with multiple template engines, django.Template.render() must receive a dictionary of context rather than Context or RequestContext. If you were passing either of the two classes, pass a dictionary instead – doing so is backwards-compatible with older versions of Django.
"

**Comment by belongwqz** [comment]
Thanks for agronick and codingjoe , I found another issiue:
method get_queryset in class ModelSelect2Mixin can not get the query well sometimes, maybe can add:
`        elif self.choices is not None:
            queryset = self.choices.queryset
`
but when I do this, the page is slow to respond, I'm not sure if the cache failed.

**Comment by codingjoe** [comment]
I don't think it's because of a cache issue, but I'd presume that the queryset gets evaluated. That is bound to be very slow the larger your table is.

**Comment by codingjoe** [comment]
Do you have an example on when the query fails?

**Comment by belongwqz** [comment]
example:
`class WallForm(forms.Form):
    source_entity = forms.ModelMultipleChoiceField(
        widget=ModelSelect2MultipleWidget(search_fields=['name__icontains']),
        queryset=Entity.objects.all())`
when render the form, raise exception:
ModelSelect2MultipleWidget is missing a QuerySet. Define ModelSelect2MultipleWidget.model, ModelSelect2MultipleWidget.queryset, or override ModelSelect2MultipleWidget.get_queryset().
when modify the method get_queryset in class ModelSelect2Mixin as said(use self.choices.queryset), it work well. It should be django 1.11 changes, but I did not in-depth tracking.

**Comment by codingjoe** [comment]
@belongwqz I opened a PR #345, feel free to review it. I'll merge and release it asap.

**Comment by codingjoe** [comment]
Should be solved in 5.9.0

**Comment by kierun** [comment]
Just updated to 5.9.0 and I am still getting the above error. Below is the stack trace. Do you need more information from me?

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 369, in run
    testMethod()
  File "/home/usr/repos/intranet/ook_intranet_site/aion/tests/views/test_assembly.py", line 149, in test_new_assembly_post_failed
    response = self.client.post(reverse('aion:new_assembly'), {})
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/test/client.py", line 548, in post
    secure=secure, **extra)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/test/client.py", line 350, in post
    secure=secure, **extra)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/test/client.py", line 416, in generic
    return self.request(**r)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/test/client.py", line 501, in request
    six.reraise(*exc_info)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/usr/repos/intranet/ook_intranet_site/aion/views/assembly.py", line 417, in new_assembly
    return render(request, 'aion/new_assembly.html', context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 207, in render
    return self._render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/loader_tags.py", line 177, in render
    return compiled_parent._render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/test/utils.py", line 107, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/loader_tags.py", line 72, in render
    result = block.nodelist.render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 990, in render
    bit = node.render_annotated(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
    return self.render(context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 1046, in render
    return render_value_in_context(output, context)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/template/base.py", line 1024, in render_value_in_context
    value = force_text(value)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/utils/encoding.py", line 78, in force_text
    s = six.text_type(s)
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/utils/html.py", line 376, in <lambda>
    klass.__unicode__ = lambda self: mark_safe(klass_unicode(self))
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/forms/boundfield.py", line 41, in __str__
    return self.as_widget()
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django/forms/boundfield.py", line 120, in as_widget
    **kwargs
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django_select2/forms.py", line 234, in render
    self.set_to_cache()
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django_select2/forms.py", line 356, in set_to_cache
    queryset = self.get_queryset()
  File "/home/usr/.virtualenvs/intranet/lib/python2.7/site-packages/django_select2/forms.py", line 408, in get_queryset
    'cls': self.__class__.__name__
NotImplementedError: MyWidget is missing a QuerySet. Define MyWidget.model, MyWidget.queryset, or override MyWidget.get_queryset().
```

**Comment by codingjoe** [comment]
@kierun that seems like an implementation issue. Can you show me how you implemented the form?

**Comment by belongwqz** [comment]
Indeed, the problem is not resolved，when add ` elif self.choices is not None:queryset = self.choices.queryset` as I said (in method get_queryset in class ModelSelect2Mixin), it can work.

**Comment by codingjoe** [comment]
Sorry, but I don't get the issue yet. Please open a PR with the fix including a test, that exploids the bug.

**Comment by kierun** [comment]
@codingjoe 

Here it is in all its simplistic glory.

```
class NewAssemblyForm(AssemblyForm):

    batch = forms.IntegerField(max_value=100,
                               min_value=1,
                               initial=1,
                               label="Create this many instances")

    class Meta:
        model = Assembly
        fields = ['configurator',
                  'project_code',
                  'description',
                  'batch',
                  'tags',
                  'created_at',
                  'created_by',
                  'locality',
                  'status',
                  'manufacturer_serial_number',
                  'customer',
                  'customer_equipment_reference',
                  'supplier',
                  'supplier_reference',
                  'sap',
                  'location_number_field',
                  ]  # yapf: disable
        widgets = {
            'configurator': MyWidget(attrs={'style': 'width:100%'}),
            'customer': Select2Widget(attrs={'style': 'min-width:300px'}),
            'supplier': Select2Widget(attrs={'style': 'min-width:300px'}),
            'locality': Select2Widget(attrs={'style': 'min-width:300px'}),
            'status': Select2Widget(attrs={'style': 'min-width:300px'}),
            'created_at': forms.TextInput(attrs={
                'class': 'datepicker',
                'type': 'test',
                'id': 'datepicker',
            }),  # yapf: disable
        }```

**Comment by belongwqz** [comment]
Strange, in django 1.10 just use like this is OK:
`class Form(forms.Form):field = forms.ModelMultipleChoiceField(widget=ModelSelect2MultipleWidget(search_fields=['name__icontains']),queryset=Model.objects.all())`

but with django 1.10 should use as follow:
`class Form(forms.Form):field = forms.ModelMultipleChoiceField(model=Model, widget=ModelSelect2MultipleWidget(search_fields=['name__icontains']),queryset=Model.objects.all())`
or
`class Form(forms.Form):field = forms.ModelMultipleChoiceField(model=Model, widget=ModelSelect2MultipleWidget(search_fields=['name__icontains'], queryset=Model.objects.all()),queryset=Model.objects.all())`

I saw the form define in testcase, parameter queryset was given, maybe the model and queryset parameters at least one given is the right way.

So, maybe this is not a issue.

**Comment by kierun** [comment]
@belongwqz We are talking about django **1.11.X**, not 1.10.X. Also, your code formatting makes it hard to see what you are doing: can you use the preview to check that your message appears correctly? "`" is for one line "```" is for a block.

**Comment by belongwqz** [comment]
@kierun Thank you, and I just update my commit above.
Make sure use the django_select2 form by widget in a field define but not in the widgets dict of class Meta.

**Comment by kierun** [comment]
@belongwqz Thank you, this makes it much easier to read.

Hum, that means that `ModelForm` classes become much more verbose than they need to be as you would have to redefine all the fields that use select2 widgets manually. If that's the way, then fine but it seems a little counter-productive.

**Comment by kierun** [comment]
Any updates on this?

**Comment by codingjoe** [comment]
I gotta be honest with you guys, I don't see how this is actually a bug in this library. Feel free to prove me wrong, but for now I will close the issue.
